### ISSUE TITLE
package com.tkporter.fabrictwitterkit

### ISSUE THREAD

**Issue by waleedarshad-vf** [tkporter/react-native-fabric-twitterkit#1]
/home/waleed/Documents/zig-android/android/app/src/main/java/com/zig/MainActivity.java:15: error: package com.tkporter.fabrictwitterkit does not exist
import com.tkporter.fabrictwitterkit.FabricTwitterKitPackage;
                                    ^
1 error
:app:compileDebugJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:compileDebugJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by tkporter** [comment]
Hi! Could you check your `settings.gradle` in `zig-android/android/settings.gradle` and see if anything is in there containing `react-native-fabric-twitterkit`? If so let me know what the matches are

**Comment by waleedarshad-vf** [comment]
It's resolved. there was problem with configuration. i just do it from scratch and it's done
