### ISSUE TITLE
FabricTwitterKit is undefined

### ISSUE THREAD

**Issue by carlosvillu** [tkporter/react-native-fabric-twitterkit#10]
Hi,

I am trying to use your module to be able to login in my iOS app with Twitter. But I always get that `FabricTwitterKit` is undefined.  And when a I try require `NativeModules` is an empty object.

My setup is,

```
react-native-cli: 1.3.0
react-native: 0.38.1
xcode: 8.1
```

I followed the instructions from Fabric and it looks good. Build is correct and the app is registered in Fabric.

Am I missing something to register the module like a native module? I am using rnpm too of course.

Thx,

C.

**Comment by tkporter** [comment]
Hey Carlos, is this still an issue for you?

**Comment by tkporter** [comment]
Going to close this for now-- let me know if it's still an issue
