### ISSUE TITLE
Update npm package?

### ISSUE THREAD

**Issue by jasongrishkoff** [tkporter/react-native-fabric-twitterkit#12]
Hey there, thanks for creating this!  Just a heads up that the npm module seems to be lagging slightly behind the github repo:
https://www.npmjs.com/package/react-native-fabric-twitterkit

Possible to update?

**Comment by tkporter** [comment]
Hey Jason, thanks for letting me know. Going to update it and release as version 0.1.0!

**Comment by jasongrishkoff** [comment]
No worries.  Also, I can't remember specifically, but I actually had to roll back my version because the updates in this pull (https://github.com/tkporter/react-native-fabric-twitterkit/commit/f89c80b4c7f7d052be3813248e85f77535d6ae09) conflicted with the setup instructions in your README.  Might be worth triple checking the two align, and apologies for not logging the conflict.

**Comment by tkporter** [comment]
I'll fix that too, seems to be just a matter of changing `FabricTwitterKitPackage.getInstance().onActivityResult(requestCode, resultCode, data);` to `FabricTwitterKitPackage.getInstance().onActivityResult(this, requestCode, resultCode, data);`. Thanks for the heads up.
