### ISSUE TITLE
Package doesn't compile on `fetchTweet` ReactMethod

### ISSUE THREAD

**Issue by yihanseattle** [tkporter/react-native-fabric-twitterkit#14]
Hi, 

Please verify that `statusesService.show(.....)` is implemented for [twitter-core 1.3.4](https://docs.fabric.io/javadocs/twittercore/1.3.4/com/twitter/sdk/android/core/services/StatusesService.html)

The [fetchTweet() function](https://github.com/tkporter/react-native-fabric-twitterkit/blob/master/Android/src/main/java/com/tkporter/fabrictwitterkit/FabricTwitterKitModule.java#L166) has compile error.

If we are correct, the actual dependency is [twitter-core 2.0.0](https://docs.fabric.io/javadocs/twitter-core/2.0.0/com/twitter/sdk/android/core/services/StatusesService.html). The project does not compile correctly. 

Please let us know how to solve this. 

Thanks!

Yi

**Comment by chrbradley** [comment]
I'm having the same issue, here's the error:

```
.../node_modules/react-native-fabric-twitterkit/Android/src/main/java/com/tkporter/fabrictwitterkit/FabricTwitterKitModule.java:166: error: method show in interface StatusesService cannot be applied to given types;
            statusesService.show(id, trim_user, include_my_retweet, null, new com.twitter.sdk.android.core.Callback<Tweet>() {
                           ^
  required: Long,Boolean,Boolean,Boolean
  found: Long,Boolean,Boolean,<null>,<anonymous Callback<Tweet>>
  reason: actual and formal argument lists differ in length
1 error
:react-native-fabric-twitterkit:compileReleaseJavaWithJavac FAILED

```

**Comment by yihanseattle** [comment]
Hi @chrbradley ,

Same error for us.

**Comment by farazs** [comment]
Yeah it seems that the code uses `show(java.lang.Long id, java.lang.Boolean trimUser, java.lang.Boolean includeMyRetweet, java.lang.Boolean includeEntities, Callback<Tweet> cb)` from twitter-core 1.3.4 but actually has a dependency on twitter-core 2.0 which has the signature `show(Long id, Boolean trimUser, Boolean includeMyRetweet, Boolean includeEntities)` for that method.

**Comment by yamade** [comment]
Oh... it was intended for 1.3.4.

Thank you for the PR. @farazs
