### ISSUE TITLE
How can I get follower after logged in ?

### ISSUE THREAD

**Issue by waleedarshad-vf** [tkporter/react-native-fabric-twitterkit#2]

**Comment by tkporter** [comment]
What do you mean by follower? You should be able to get the profile with `fetchProfile` https://github.com/tkporter/react-native-fabric-twitterkit/blob/master/FabricTwitterKit/FabricTwitterKit.m#L37

**Comment by waleedarshad-vf** [comment]
I am taking about follower @tkporter . api from twitter https://dev.twitter.com/rest/reference/get/followers/list

**Comment by tkporter** [comment]
Doesn't seem like there is that functionality at the moment. Feel free to submit a PR if you end up needing this :)
