### ISSUE TITLE
Exception 'Attempted to call TwitterKit'

### ISSUE THREAD

**Issue by RUIFERNANDE5** [tkporter/react-native-fabric-twitterkit#24]
Thanks for creating this repo. 
However, I'm having trouble implementing the login method on ios.

The error:
> Exception 'Attempted to call TwitterKit methods before calling the requisite start methods; you must call +[Fabric with:@[Twitter class]] before using the methods on TwitterKit. If you are not storing your consumerKey and consumerSecret in your application's info.plist you must also call -[TwitterKit startWithConsumerKey:consumerSecret:] before calling +[Fabric with:]' was thrown while invoking login on target FabricTwitterKit with params (
>     17
> )

Im not sure if this is an issue with react-native-fabric-twitterkit itself or fabric. However Im correctly storing the consumerKey and consumerSecret on my info.plist.
I'm not really into java so I can't really understand FabricTwitterKitModule.java functions.

My code:
`FabricTwitterKit.login((error, res) => {
                    console.log('errors => ',error);
                    console.log('res => ',res);
                });`

Thanks in advance.
P.s: I think your npm is not up to date with the latest commits.

**Comment by RUIFERNANDE5** [comment]
A Login example would also be great. I've been able to run it on android but on account authorize the login method doesn't return a value and after if i perform a second call I always get "Authorize failed."

**Comment by mdstaff** [comment]
I'm having this problem as well and I would appreciate any advice from the maintainer and any watchers.

I'm currently using the following in my app/build.gradle:

    // Twitter
    compile 'com.twitter.sdk.android:twitter-core:3.1.1'
    compile 'com.twitter.sdk.android:tweet-composer:3.1.1'
