### ISSUE TITLE
Android login issues, RN 0.29 - 'TwitterLoginButton requires an activity.'

### ISSUE THREAD

**Issue by hazelw** [tkporter/react-native-fabric-twitterkit#3]
Hello!

Firstly, thanks for providing a library for TwitterKit in React Native.

I'm in the process of porting my app from react-native-fabric to your react-native-fabric-twitterkit using the instructions in the readme. The only piece of functionality I need is login. Unfortunately, when I call it, I get the following error:

![screen shot 2016-09-07 at 13 48 11](https://cloud.githubusercontent.com/assets/10687579/18312451/c52471fa-7501-11e6-9d56-e9b64ba34c15.png)

I'm currently using RN 0.29 with the intention of going up to 0.32. Have tested with RN 0.30 with the same result.

Are you accepting PRs on this repo?

**Comment by tkporter** [comment]
Hey there! PRs are more than welcome-- I'd appreciate the help :)

I'll look more into this though

**Comment by hazelw** [comment]
Found the problem - in the login() method on FabricTwitterKitModule, a ReactContext is passed in to the TwitterLoginButton constructor where it's expecting an Activity. I've fixed it on a fork and it's working nicely on RN 0.29, will check for backwards compatibility then submit a PR if it's good.

**Comment by tkporter** [comment]
Awesome, I appreciate it!

I originally made this repo for a project at work only using `composeTweet` so I didn't put much time into testing/debugging a lot of the other methods. Glad you found the issue!

**Comment by yamade** [comment]
Hi guys,
I've seen the same issue on Android.
When are you guys going to fix this issue?? I've seen the fix on a branch of @hazelw forked repo.

Thanks

**Comment by hazelw** [comment]
This is now fixed in the main repo.

**Comment by ronak301** [comment]
To fix this: 
1) change package.json to : `"react-native-fabric-twitterkit": "github:tkporter/react-native-fabric-twitterkit#69df5f1ed6abee40a2bd9d0404761752d58cf720" `
2) change line in mainactivity.java from `FabricTwitterKitPackage.getInstance().onActivityResult(requestCode, resultCode, data);` to `FabricTwitterKitPackage.getInstance().onActivityResult(this, requestCode, resultCode, data);`

**Comment by tkporter** [comment]
Hey @ronak301, I just updated the npm package to version 0.1.0. It's now up to date with everything on github so you should be safe to change part 1 back to normal!
