### ISSUE TITLE
How to use Login?

### ISSUE THREAD

**Issue by DannyAziz** [tkporter/react-native-fabric-twitterkit#30]
When I use the login function and once I've connected via the Twitter app my callback does nothing.

I've also tried adding NSLog to the FabricTwitterKit.m but they also don't show anything.

Here is my code: 
`FabricTwitterKit.login((error, res) => {
                    console.log('errors => ',error);
                    console.log('res => ',res);
                  });`

Any help? Thanks!

**Comment by DannyAziz** [comment]
Okay worked out what I was doing wrong.

You need to follow the docs properly: https://dev.twitter.com/twitterkit/ios/log-in-with-twitter

My mistake was not adding: 
```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {
    return [[Twitter sharedInstance] application:app openURL:url options:options];
}
``` 
to my AppDelgate.

**Comment by aschenkel** [comment]
Hi..
I'm having some trouble understanding exactly how to write login or fetchtweet request from the iOS functions on FabricTwitterKit.m file.

Could you help me with any example?

**Comment by DannyAziz** [comment]
@aschenkel Hey!

If you've set it up properly (Follow the docs and read my comment above), all you need to do is import the module and call the function

```
// Import
import FabricTwitterKit from 'react-native-fabric-twitterkit'

// Login Function
FabricTwitterKit,login((response) => {
    // Callback here
})
```

Let me know if you need more help!

**Comment by aschenkel** [comment]
Thanks man! 
I'm already logged in and fetch the profile. I had to change deployment target to 9.0 on iOS, weird.
I'm trying to fetchTweets now.

```
fetchTweets() {
        //Declare myMap
        FabricTwitterKit.fetchTweet(myMap,(res) => 
        {
            if(res !== undefined){
                console.log(res);
                //dispatch actions
            }
        });
    }
```

and I have declared myMap in many ways:

       var myMap = new Map();
        var valueID = this.props.userID,
        keyID = "id";
        myMap.set(keyID, valueID);
---------------------------------------
        var myMap = []; 
        myMap.push({
            key:   "id",
            value: this.props.userID
        });
---------------------------------------
        var myMap = {
            key:   "id",
            value: this.props.userID
        }

but I'm always getting 2 exceptions

1) 

> JSON value '(
>         {
>         key = id;
>         value = 881887373335957504;
>     }
> )' of type NSMutableArray cannot be converted to NSDictionary
> 

2)

>  Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]' was thrown while invoking fetchTweet on target FabricTwitterKit with params (
>         (
>                 {
>             key = id;
>             value = 881887373335957504;
>         }
>     ),
>     201
> )

Do you have any idea what would be the right way?

**Comment by DannyAziz** [comment]
@aschenkel This is just a guess, but try this to declare `myMap`

`var myMap = {id: 881887373335957504 } `

**Comment by aschenkel** [comment]
Nice try but it throws

> Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]' was thrown while invoking fetchTweet on target FabricTwitterKit with params (
>         {
>         id = 881887373335957504;
>     },
>     207
> )

Same with:

```
var myMap = {"id": 881887373335957504 }
```

**Comment by aschenkel** [comment]
works with 
```
var myMap = {
      "id": "881887373335957504",
       "trim_user": "false",
       "include_my_retweet": "false"
 }

```

**Comment by nicoaureliovillanueva** [comment]
Hi @DannyAziz i used this function 

```
FabricTwitterKit.login((response) => {
    // Callback here

      console.log('Twitter Data Response ' + response);
      })
```

the return is "Twitter Data Response null".. Please help me how can i get proper syntax for Twitter login... Im new in react native.. Thanks sir!

**Comment by nicoaureliovillanueva** [comment]
is it posible to get email from twitter?
