### ISSUE TITLE
Feature request: ability to load Tweets

### ISSUE THREAD

**Issue by yamade** [tkporter/react-native-fabric-twitterkit#4]
Hi,

I think its a really great amount of good work, but I would like to more functionality to this module, I would like to be able to load Tweets too.

Do you have any plan to add more functionality?

**Comment by yamade** [comment]
Hi again,

Can I create a PR to add load tweets?

**Comment by tkporter** [comment]
Hi, I've been busy with school so I haven't had much time to look at this-- PRs are more than welcome!

**Comment by yamade** [comment]
I got it. 
Let me try. Thanks.

**Comment by Liroo** [comment]
Any news about this issue ? 👍

**Comment by yamade** [comment]
I have the PR in local. But it's like taking time to approve to publish it from manager since this is a part of my work so... Please wait a moment.

**Comment by yamade** [comment]
@tkporter Just make sure. A legal department want to know. This react-native-fabric-twitterkit package is MIT license, right?

**Comment by tkporter** [comment]
Yes, I'll make that clear on the repo when I get to my laptop.

**Comment by yamade** [comment]
Thank you!

**Comment by Liroo** [comment]
Hey @yamade, any 🆕 s about tweet loading on RN ?

**Comment by yamade** [comment]
@Liroo Thank you so much for your patience. Approval process was quite tough. I don't like it honestly... Anyway the process is going to be changed fortunately by my effort so I'm just waiting. I believe it's going to be within a week.

**Comment by Liroo** [comment]
@yamade No problem, really interested to see your work so I can wait ;)

**Comment by yamade** [comment]
@tkporter @Liroo If you have a time, please take a look the PR https://github.com/tkporter/react-native-fabric-twitterkit/pull/11

**Comment by tkporter** [comment]
Merged! Thanks for everything and look forward to 0.1.0!
