### ISSUE TITLE
FabricTwitterKitModule not override abstract method onNewIntent(Intent)

### ISSUE THREAD

**Issue by huangmr** [tkporter/react-native-fabric-twitterkit#8]
I am getting the following build error while trying to build the android side with this lib, have I missed anything?

Error:(28, 8) error: FabricTwitterKitModule is not abstract and does not override abstract method onNewIntent(Intent) in ActivityEventListener

Versions I'm using:
    "react-native-fabric": "^0.3.0",
    "react-native-fabric-twitterkit": "0.0.1",

Android sdk:
        compileSdk = 24
        buildTools = "24.0.2"
        minSdk = 16
        targetSdk = 22
        supportLibraryVersion = '24.2.1'

**Comment by huangmr** [comment]
Okey, this maybe RN 0.34.1 break.

**Comment by tkporter** [comment]
Just merged, great job and thanks!
